bigapple2018/EC

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb

bootstrap設定、ヘッダー・フッターの表示

---

app/controllers/users/registrations_controller.rb
app/views/users/registrations/new.html.erb

/users/sign_up から画面表示、及び登録、ログインまで確認済みです。

signup画面　仮作成(登録の確認まで)

---

app/assets/javascripts/carts.coffee
app/assets/stylesheets/carts.scss
app/controllers/carts_controller.rb
app/helpers/carts_helper.rb
app/views/admins/sessions/new.html.erb
test/controllers/carts_controller_test.rb

アドミンのサインインを変更

---

app/controllers/sub_addresses_controller.rb

subbadress controller ridirect先修正

Subaddress new narita

---

app/controllers/sub_addresses_controller.rb
app/views/sub_addresses/index.html.erb
config/routes.rb

画面表示および、リンク先ボタンに関しては、表示がわかりにくかったため仮ボタンで実装

subaddress一覧画面表示 一部subaddresscontoroller修正

---

app/assets/stylesheets/items.scss
app/models/item.rb
app/views/items/index.html.erb
config/routes.rb

Items index 2 moro

---

app/views/users/sessions/new.html.erb
config/locales/devise.ja.yml

利用者Signin画面　サインイン画面エラー表示・デザイン対応”

---

app/views/items/index.html.erb

商品一覧画面　ジャンル画像タグの削除

---

app/controllers/admins/users_controller.rb
app/controllers/admins_controller.rb
app/views/admins/sessions/new.html.erb
app/views/admins/top.html.erb
app/views/admins/users/index.html.erb

Admins top shuusei mutou

---

app/assets/stylesheets/carts.scss
app/controllers/carts_controller.rb
app/views/carts/comfirm.html.erb
config/routes.rb

購入確認画面完了 viewファイル追加

---

app/views/layouts/_userHeader.html.erb

・検索フォームの表示切り替え判定を修正
・ログイン後のHomeメニュー追加
・MyPageのリンクを修正、遷移可能にしました

利用者サイトヘッダー修正

---

db/migrate/20180424052530_add_iteminfo_to_order_history_items.rb
db/schema.rb
db/seeds.rb

・price,artist,title_name 列が抜けていたため追加
・購入履歴開発用デモデータの挿入seed更新

order_history_itemsテーブルに列が不足しているため追加

---

app/assets/stylesheets/application.scss
app/views/layouts/_adminHeader.html.erb
app/views/layouts/_userHeader.html.erb

・管理者サイトの画面遷移時の表示内容切り替えを追加
・利用者サイト・管理者サイトのメニュー表示位置調整

管理者サイト・利用者サイトのヘッダー表示を修正

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/users/registrations/new.html.erb
vendor/assets/javascript/jquery.jpostal.js

郵便番号入力による住所自動入力機能を追加（jpostal.jsというライブラリを使っています)
サインアップ画面の住所欄をテキストエリアに修正

利用者サイトサインアップ　郵便番号入力による住所自動入力追加

---

app/controllers/order_histories_controller.rb
app/controllers/sub_addresses_controller.rb
app/controllers/users_controller.rb

現在終了画面にログインユーザー の識別機能追加
各controllerに実装の方が楽かと思い致しました。

各ログインユーザー判断機能実装

---

app/assets/stylesheets/items.scss
app/views/items/index.html.erb
app/views/items/show.html.erb

商品詳細画面　デザイン修正

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
app/views/users/registrations/new.html.erb
app/views/users/sessions/new.html.erb

サインイン・サインアップの見出しのフォント修正、タイトルの修正

---

app/views/layouts/_userHeader.html.erb

logo画像リンク先追加

---

app/assets/stylesheets/order_histories.scss
app/assets/stylesheets/sub_addresses.scss
app/views/users/show.html.erb
config/routes.rb

pathに不要な情報を渡していたため削除
routing変更
cssの微調整

サブ住所 購入履歴routing css変更

---

app/views/admins/order_history/index.html.erb
app/views/admins/users/edit.html.erb
app/views/admins/users/show.html.erb

管理者サイト　ユーザの購入履歴画面への遷移口を追加

---

app/assets/stylesheets/admin/items.scss
app/assets/stylesheets/application.scss
app/controllers/admins/cd_items_controller.rb
app/controllers/admins/items_controller.rb
app/models/cd_item.rb
app/models/item.rb
app/models/song.rb
app/views/admins/cd_items/edit.html.erb
app/views/admins/items/edit.html.erb
app/views/admins/items/index.html.erb
app/views/admins/items/new.html.erb
app/views/layouts/application.html.erb
config/locales/ja.yml

CD、収録曲の登録・編集を実装
CDのジャケットの編集を追加

商品登録・編集周りの修正
